/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queue;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author Nugraha
 */
public class QueueUI2 extends javax.swing.JFrame {
    
    int xMouse;
    int yMouse;
    int timeRun = 0;

    /**
     * Creates new form Home
     */
    public QueueUI2() {
        initComponents();
        inputX.setText("");
        varx.setText(""); 
        vary.setText(""); 
        var1.setText(""); 
        var2.setText(""); 
        var3.setText(""); 
        var3.setText(""); 
        var4.setText(""); 
        var5.setText(""); 
        var6.setText(""); 
        var7.setText(""); 
        var8.setText(""); 
        notes.setVisible(false);
        pKanan4.setVisible(true);
        
        head2.setVisible(false);
        head3.setVisible(false);
        head1.setVisible(false);
        tail1.setVisible(false);
        tail2.setVisible(false);
        tail4.setVisible(false);
        tail3.setVisible(false);
        
        
        
        
        setLocationRelativeTo(this);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        page = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        inputX = new javax.swing.JTextField();
        enqueue = new javax.swing.JPanel();
        TF1 = new javax.swing.JLabel();
        dequeue = new javax.swing.JPanel();
        TF2 = new javax.swing.JLabel();
        check = new javax.swing.JPanel();
        TF3 = new javax.swing.JLabel();
        var1 = new javax.swing.JTextField();
        vary = new javax.swing.JTextField();
        var2 = new javax.swing.JTextField();
        var3 = new javax.swing.JTextField();
        var4 = new javax.swing.JTextField();
        var5 = new javax.swing.JTextField();
        varx = new javax.swing.JTextField();
        notes = new javax.swing.JLabel();
        pKiri1 = new javax.swing.JLabel();
        pKiri4 = new javax.swing.JLabel();
        pKiri2 = new javax.swing.JLabel();
        pKiri3 = new javax.swing.JLabel();
        pKanan4 = new javax.swing.JLabel();
        pKanan3 = new javax.swing.JLabel();
        pKanan2 = new javax.swing.JLabel();
        pKanan1 = new javax.swing.JLabel();
        var6 = new javax.swing.JTextField();
        note9 = new javax.swing.JLabel();
        note10 = new javax.swing.JLabel();
        note11 = new javax.swing.JLabel();
        note12 = new javax.swing.JLabel();
        var8 = new javax.swing.JTextField();
        var7 = new javax.swing.JTextField();
        head2 = new javax.swing.JTextField();
        head3 = new javax.swing.JTextField();
        head1 = new javax.swing.JTextField();
        tail1 = new javax.swing.JTextField();
        tail2 = new javax.swing.JTextField();
        tail4 = new javax.swing.JTextField();
        tail3 = new javax.swing.JTextField();
        title = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        page.setBackground(new java.awt.Color(255, 255, 255));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(122, 71, 221));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        page.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 107, 20, 280));

        jSeparator2.setBackground(new java.awt.Color(122, 71, 221));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        page.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 20, 280));

        jSeparator5.setForeground(new java.awt.Color(122, 71, 221));
        page.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 100, 10));

        jSeparator6.setForeground(new java.awt.Color(122, 71, 221));
        page.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 100, 10));

        jSeparator7.setForeground(new java.awt.Color(122, 71, 221));
        page.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 100, 10));

        inputX.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        inputX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputX.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 71, 221)), " Data ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 14), new java.awt.Color(122, 71, 221))); // NOI18N
        page.add(inputX, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, 70));

        enqueue.setBackground(new java.awt.Color(255, 255, 255));
        enqueue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 71, 221)));
        enqueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enqueueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enqueueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enqueueMouseExited(evt);
            }
        });
        enqueue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TF1.setFont(new java.awt.Font("Kristen ITC", 1, 20)); // NOI18N
        TF1.setForeground(new java.awt.Color(204, 204, 204));
        TF1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TF1.setText("Enqueue");
        enqueue.add(TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, 130, 40));

        page.add(enqueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 200, 60));

        dequeue.setBackground(new java.awt.Color(255, 255, 255));
        dequeue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 71, 221)));
        dequeue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dequeueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dequeueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dequeueMouseExited(evt);
            }
        });
        dequeue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TF2.setFont(new java.awt.Font("Kristen ITC", 1, 20)); // NOI18N
        TF2.setForeground(new java.awt.Color(204, 204, 204));
        TF2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TF2.setText("Dequeue");
        dequeue.add(TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, 40));

        page.add(dequeue, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 360, 60));

        check.setBackground(new java.awt.Color(255, 255, 255));
        check.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 71, 221)));
        check.setPreferredSize(new java.awt.Dimension(200, 175));
        check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                checkMousePressed(evt);
            }
        });
        check.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TF3.setFont(new java.awt.Font("Kristen ITC", 1, 20)); // NOI18N
        TF3.setForeground(new java.awt.Color(204, 204, 204));
        TF3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TF3.setText("Clear");
        check.add(TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 10, 90, 40));

        page.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 360, 60));

        var1.setEditable(false);
        var1.setBackground(new java.awt.Color(255, 255, 255));
        var1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        var1.setForeground(new java.awt.Color(122, 71, 221));
        var1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var1.setText("var1");
        var1.setBorder(null);
        page.add(var1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 80, 70));

        vary.setEditable(false);
        vary.setBackground(new java.awt.Color(255, 255, 255));
        vary.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        vary.setForeground(new java.awt.Color(122, 71, 221));
        vary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vary.setBorder(null);
        page.add(vary, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 80, 70));

        var2.setEditable(false);
        var2.setBackground(new java.awt.Color(255, 255, 255));
        var2.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        var2.setForeground(new java.awt.Color(122, 71, 221));
        var2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var2.setText("var2");
        var2.setBorder(null);
        page.add(var2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 60, 50));

        var3.setEditable(false);
        var3.setBackground(new java.awt.Color(255, 255, 255));
        var3.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        var3.setForeground(new java.awt.Color(122, 71, 221));
        var3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var3.setText("var3");
        var3.setBorder(null);
        page.add(var3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 60, 50));

        var4.setEditable(false);
        var4.setBackground(new java.awt.Color(255, 255, 255));
        var4.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        var4.setForeground(new java.awt.Color(122, 71, 221));
        var4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var4.setText("var4");
        var4.setBorder(null);
        page.add(var4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 60, 50));

        var5.setEditable(false);
        var5.setBackground(new java.awt.Color(255, 255, 255));
        var5.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        var5.setForeground(new java.awt.Color(122, 71, 221));
        var5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var5.setText("var5");
        var5.setBorder(null);
        page.add(var5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 60, 50));

        varx.setEditable(false);
        varx.setBackground(new java.awt.Color(255, 255, 255));
        varx.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        varx.setForeground(new java.awt.Color(122, 71, 221));
        varx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        varx.setBorder(null);
        page.add(varx, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 80, 70));

        notes.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        notes.setForeground(new java.awt.Color(122, 71, 221));
        notes.setText("* FULL");
        page.add(notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 90, 40));

        pKiri1.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        pKiri1.setForeground(new java.awt.Color(122, 71, 221));
        pKiri1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pKiri1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Down_25px.png"))); // NOI18N
        page.add(pKiri1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 90, 30));

        pKiri4.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        pKiri4.setForeground(new java.awt.Color(204, 204, 204));
        pKiri4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pKiri4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Down_25px.png"))); // NOI18N
        page.add(pKiri4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 90, 30));

        pKiri2.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        pKiri2.setForeground(new java.awt.Color(122, 71, 221));
        pKiri2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pKiri2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Down_25px.png"))); // NOI18N
        page.add(pKiri2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 90, 30));

        pKiri3.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        pKiri3.setForeground(new java.awt.Color(204, 204, 204));
        pKiri3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pKiri3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Down_25px.png"))); // NOI18N
        page.add(pKiri3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 90, 30));

        pKanan4.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        pKanan4.setForeground(new java.awt.Color(122, 71, 221));
        pKanan4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pKanan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Down_25px.png"))); // NOI18N
        page.add(pKanan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, 90, 30));

        pKanan3.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        pKanan3.setForeground(new java.awt.Color(122, 71, 221));
        pKanan3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pKanan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Down_25px.png"))); // NOI18N
        page.add(pKanan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, 90, 30));

        pKanan2.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        pKanan2.setForeground(new java.awt.Color(122, 71, 221));
        pKanan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pKanan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Down_25px.png"))); // NOI18N
        page.add(pKanan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 90, 30));

        pKanan1.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        pKanan1.setForeground(new java.awt.Color(122, 71, 221));
        pKanan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pKanan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Down_25px.png"))); // NOI18N
        page.add(pKanan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, 90, 30));

        var6.setEditable(false);
        var6.setBackground(new java.awt.Color(255, 255, 255));
        var6.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        var6.setForeground(new java.awt.Color(122, 71, 221));
        var6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var6.setText("var6");
        var6.setBorder(null);
        page.add(var6, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 400, 80, 60));

        note9.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        note9.setForeground(new java.awt.Color(122, 71, 221));
        note9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        note9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Down_25px.png"))); // NOI18N
        page.add(note9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 90, 30));

        note10.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        note10.setForeground(new java.awt.Color(122, 71, 221));
        note10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        note10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Left_25px.png"))); // NOI18N
        page.add(note10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 90, 40));

        note11.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        note11.setForeground(new java.awt.Color(122, 71, 221));
        note11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        note11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Left_25px.png"))); // NOI18N
        page.add(note11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 90, 40));

        note12.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        note12.setForeground(new java.awt.Color(122, 71, 221));
        note12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        note12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Chevron_Left_25px.png"))); // NOI18N
        page.add(note12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 90, 40));

        var8.setEditable(false);
        var8.setBackground(new java.awt.Color(255, 255, 255));
        var8.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        var8.setForeground(new java.awt.Color(122, 71, 221));
        var8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var8.setText("var8");
        var8.setBorder(null);
        page.add(var8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 70, 60));

        var7.setEditable(false);
        var7.setBackground(new java.awt.Color(255, 255, 255));
        var7.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        var7.setForeground(new java.awt.Color(122, 71, 221));
        var7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var7.setText("var7");
        var7.setBorder(null);
        page.add(var7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 80, 60));

        head2.setEditable(false);
        head2.setBackground(new java.awt.Color(255, 255, 255));
        head2.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        head2.setForeground(new java.awt.Color(122, 71, 221));
        head2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        head2.setText("*Head");
        head2.setBorder(null);
        page.add(head2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 110, 50));

        head3.setEditable(false);
        head3.setBackground(new java.awt.Color(255, 255, 255));
        head3.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        head3.setForeground(new java.awt.Color(122, 71, 221));
        head3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        head3.setText("*Head");
        head3.setBorder(null);
        page.add(head3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, 110, 50));

        head1.setEditable(false);
        head1.setBackground(new java.awt.Color(255, 255, 255));
        head1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        head1.setForeground(new java.awt.Color(122, 71, 221));
        head1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        head1.setText("*Head");
        head1.setBorder(null);
        head1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                head1ActionPerformed(evt);
            }
        });
        page.add(head1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 110, 50));

        tail1.setEditable(false);
        tail1.setBackground(new java.awt.Color(255, 255, 255));
        tail1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tail1.setForeground(new java.awt.Color(122, 71, 221));
        tail1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tail1.setText("Tail *");
        tail1.setBorder(null);
        page.add(tail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 110, 50));

        tail2.setEditable(false);
        tail2.setBackground(new java.awt.Color(255, 255, 255));
        tail2.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tail2.setForeground(new java.awt.Color(122, 71, 221));
        tail2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tail2.setText("Tail *");
        tail2.setBorder(null);
        tail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tail2ActionPerformed(evt);
            }
        });
        page.add(tail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 110, 50));

        tail4.setEditable(false);
        tail4.setBackground(new java.awt.Color(255, 255, 255));
        tail4.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tail4.setForeground(new java.awt.Color(122, 71, 221));
        tail4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tail4.setText("Tail *");
        tail4.setBorder(null);
        page.add(tail4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 110, 50));

        tail3.setEditable(false);
        tail3.setBackground(new java.awt.Color(255, 255, 255));
        tail3.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tail3.setForeground(new java.awt.Color(122, 71, 221));
        tail3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tail3.setText("Tail *");
        tail3.setBorder(null);
        page.add(tail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 110, 50));

        jPanel2.add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 1050, 540));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleMouseDragged(evt);
            }
        });
        title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleMousePressed(evt);
            }
        });
        title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(122, 71, 221));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X ");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        title.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 50, 50));

        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void doexit()
    {
        int confirm = JOptionPane.showConfirmDialog(null, 
                "Apakah anda yakin ingin keluar dari program?", "Tutup Aplikasi",
                JOptionPane.YES_NO_OPTION);    
        
        if (confirm == JOptionPane.YES_OPTION){
        System.exit(0);
    }
    
    }
    
    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        doexit();
    }//GEN-LAST:event_ExitMouseClicked

    private void titleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_titleMouseDragged

    private void titleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titleMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void enqueueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enqueueMouseClicked
        // TODO add your handling code here:
        
      String data = inputX.getText();
        String a1 = varx.getText(); 
        String a2 = vary.getText(); 
        String b = var1.getText(); 
        String c = var2.getText();  
        String e = var3.getText(); 
        String f = var4.getText(); 
        String g = var5.getText(); 
        String h = var6.getText(); 
        
         if (data.equals("")){
       JOptionPane.showMessageDialog(null,"Enter data!");    
       
        }else {
             if (g.equals("")){
            
        Thread th=new Thread(){
            @Override
            public void run (){
                try{
                    for(int a=0;a<=10;a++){
                        Thread.sleep(1000);
                        if (a==1){run1();}
                        if (a==2){run2();}
                        if (a==3){run3();}
                        if (a==4){run4();}
                        if (a==5){run5();}
                        if (a==6){run6();}
                    }
                }catch (Exception ex){
                    System.out.println(ex);
                }
            }
        };th.start();
        
         } else if (e.equals("")){
                    Thread th=new Thread(){
            @Override
            public void run (){
                try{
                    for(int a=0;a<=10;a++){
                        Thread.sleep(1000);
                        if (a==1){run1();}
                        if (a==2){run2();}
                        if (a==3){run3();}
                        if (a==4){run4();}
                        if (a==5){run5();}
                        if (a==6){run6();}
                    }
                }catch (Exception ex){
                    System.out.println(ex);
                }
            }
        };th.start();
        
                } else if (e.equals("")){
                    Thread th=new Thread(){
            @Override
            public void run (){
                try{
                    for(int a=0;a<=10;a++){
                        Thread.sleep(1000);
                        if (a==1){run1();}
                        if (a==2){run2();}
                        if (a==3){run3();}
                        if (a==4){run4();}
                        if (a==5){run5();}
                        if (a==6){run6();}
                    }
                }catch (Exception ex){
                    System.out.println(ex);
                }
            }
        };th.start();
        
                }
             
             
             
             
             
             
        } 
                
                
    }//GEN-LAST:event_enqueueMouseClicked

    
    private void run1(){
        String data = varx.getText();
        String input = inputX.getText();

        
       if (data.equals("")){
           
       varx.setText(input);
        }
    
    }
    
    private void run2(){
        String data = var1.getText();
        String input = varx.getText();

        
       if (data.equals("")){
           
       var1.setText(input);
       varx.setText("");
        }
    
    }
    
    private void run3(){
        String data = var2.getText();
        String a1 = var1.getText(); 
        
        String d = var3.getText(); 
        String e = var4.getText(); 
        String f = var5.getText(); 
        
        
       if (data.equals("")){
       var2.setText(a1);
       var1.setText("");
       
       if(e.equals("") && f.equals("") && !d.equals("")){
            
            
            pKanan3.setVisible(false);
            head3.setVisible(true);
            
            pKanan1.setVisible(true);
            head1.setVisible(false);
            
            pKanan2.setVisible(true);
            head2.setVisible(false);
    }
       
        } else {
           vary.setText(a1);
           var1.setText("");
           notes.setVisible(true);
           pKanan4.setVisible(false);
       }
    }
    
    private void run4(){
        String data = var3.getText();
        String a12 = var2.getText(); 
        
        
       if (data.equals("")){
       var3.setText(a12);
       var2.setText("");
       }   
    }
    
    private void run5(){
        String data = var4.getText();
        String a13 = var3.getText(); 
        String e = var3.getText(); 
        String f = var4.getText(); 
        
        
       if (data.equals("")){
       var4.setText(a13);
       var3.setText("");
       
       if(f.equals("") && !e.equals("") ){
            pKanan2.setVisible(false);
            head2.setVisible(true);
            
            pKanan3.setVisible(true);
            head3.setVisible(false);
            
            pKanan1.setVisible(true);
            head1.setVisible(false);
            
    }
        } 
    }
    
    private void run6(){
        String data = var5.getText();
        String a14 = var4.getText(); 
        String f = var4.getText(); 
        String g = var5.getText(); 
        
        
       if (data.equals("")){
       var5.setText(a14);
       var4.setText("");
       
       if(g.equals("") && !f.equals("") ){
            pKanan1.setVisible(false);
            head1.setVisible(true);
            
            pKanan3.setVisible(true);
            head3.setVisible(false);
            
            pKanan2.setVisible(true);
            head2.setVisible(false);
    }
        }
    }
    
    public void checkHead(){
        
        String d = var2.getText(); 
        String e = var3.getText(); 
        String f = var4.getText(); 
        String g = var5.getText(); 
        String h = var6.getText(); 
        
        
        if( g.equals("") && !f.equals("") ){
            
            pKanan1.setVisible(false);
            head1.setVisible(true);
            
            pKanan3.setVisible(true);
            head3.setVisible(false);
            
            pKanan2.setVisible(true);
            head2.setVisible(false);
            
            
            
        } else if(f.equals("") && !e.equals("") ){
            pKanan2.setVisible(false);
            head2.setVisible(true);
            
            pKanan3.setVisible(true);
            head3.setVisible(false);
            
            pKanan1.setVisible(true);
            head1.setVisible(false);
            
    } else if(e.equals("") && f.equals("") && !d.equals("")){
            
            
            pKanan3.setVisible(false);
            head3.setVisible(true);
            
            pKanan1.setVisible(true);
            head1.setVisible(false);
            
            pKanan2.setVisible(true);
            head2.setVisible(false);
    }
    }
    
    private void run7(){
        Thread th=new Thread(){
            @Override
            public void run (){
                try{
                    for(int a=0;a<=7;a++){
                        Thread.sleep(800);
                        if (a==1){run7a();}
                        if (a==2){run7b();}
                        if (a==3){run7c();}
                        if (a==4){run7d();}
                        if (a==5){checkHead();}
                    }
                }catch (Exception ex){
                    System.out.println(ex);
                }
            }
        };th.start();
        
        
        
        
         
//    }
//        private void run8a(){
//        Thread th1=new Thread(){
//            @Override
//            public void run (){
//                try{
//                    for(int a=0;a<=7;a++){
//                        Thread.sleep(800);
//                        if (a==1){run7a();}
//                        if (a==2){run7b();}
//                        if (a==3){run7c();}
//                        if (a==4){run7d();}
//                        if (a==5){checkHead();}
//                    }
//                }catch (Exception ex){
//                    System.out.println(ex);
//                }
//            }
//        };th1.start();
//        
//        
//        
        
         
    }
    private void run7a(){
        String data = var5.getText();
        var6.setText(data);
        var5.setText("");
    }
    
     private void run7b(){
        String data = var6.getText();
        var7.setText(data);
        var6.setText("");
        checkHead();
    }
    
     private void run7c(){
        String data = var7.getText();
        var7.setText("");
        var8.setText(data);
        
    }
    
     private void run7d(){
         String data = var7.getText();
         var7.setText(data);
         var8.setText(data);
    }
    
    private void enqueueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enqueueMouseEntered
        // TODO add your handling code here:
        x1();
    }//GEN-LAST:event_enqueueMouseEntered

     public void x1() {
        setColor(enqueue);
        setColorTF(TF1);
        setBorder2(enqueue);
    }
     
    private void enqueueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enqueueMouseExited
        // TODO add your handling code here:
        y1();
    }//GEN-LAST:event_enqueueMouseExited

    public void y1() {
        resetColor(enqueue);
        resetColorTF(TF1);
    }
    
    private void dequeueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dequeueMouseEntered
        // TODO add your handling code here:
        x2();
    }//GEN-LAST:event_dequeueMouseEntered

    public void x2() {
        setBorder2(dequeue);
        setColor(dequeue);
        setColorTF(TF2);
    }
    
    private void dequeueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dequeueMouseExited
        // TODO add your handling code here:
        y2();
    }//GEN-LAST:event_dequeueMouseExited

    public void y2() {
        resetColorTF(TF2);
        resetColor(dequeue);
    }
    
    private void checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseClicked
        // TODO add your handling code here:
        String b = var1.getText(); 
        String c = var2.getText(); 
        String d = var3.getText(); 
        String e = var4.getText(); 
        String f = var5.getText(); 
 
    }//GEN-LAST:event_checkMouseClicked

    private void checkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseEntered
        // TODO add your handling code here:
        x3();
    }//GEN-LAST:event_checkMouseEntered

    public void x3() {
        setColor(check);
        setBorder2(check);
        setColorTF(TF3);
    }
    
    private void checkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseExited
        // TODO add your handling code here:
        y3();
    }//GEN-LAST:event_checkMouseExited

    public void y3() {
        resetColorTF(TF3);
        resetColor(check);
    }
    
    private void checkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMousePressed

    private void dequeueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dequeueMouseClicked
        // TODO add your handling code here:
        String b = var1.getText(); 
        String c = var2.getText(); 
        String d = var3.getText(); 
        String e = var4.getText(); 
        String f = var5.getText();
        String g = var6.getText(); 
        String h = var7.getText(); 
        String i = var8.getText(); 
        
        if(g.equals("") && !(f.equals(""))){
            run7();
            
        } else if (c.equals("") && !d.equals("")){
    } else if (d.equals("") && !e.equals("")){
    } else if (e.equals("") && !f.equals("")){
    }
        
        
    }//GEN-LAST:event_dequeueMouseClicked

    private void head1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_head1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_head1ActionPerformed

    private void tail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tail2ActionPerformed

    
    

    
    
public void resetColor(JPanel panel)
    {
        panel.setBackground(new java.awt.Color(204, 255, 204));
    }

public void setColor(JPanel panel)
    {
        panel.setBackground(new java.awt.Color(122,71,221));
    }
      
    
    public void setBorder2(JPanel panel)
    {
    panel.setBorder(new LineBorder(new java.awt.Color(112, 71, 221)));
    }    
    
    public void resetBorder(JPanel panel)
    {
    panel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }
    
    public void setColorTF(JLabel label)
    {
        label.setForeground(new java.awt.Color(204,255,204));
    }

public void resetColorTF(JLabel label)
    {
        label.setForeground(new java.awt.Color(204,204,204));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueueUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueueUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueueUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueueUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //var1r-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //var1r-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //var1r-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //var1r-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueueUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel TF1;
    private javax.swing.JLabel TF2;
    private javax.swing.JLabel TF3;
    private javax.swing.JPanel check;
    private javax.swing.JPanel dequeue;
    private javax.swing.JPanel enqueue;
    private javax.swing.JTextField head1;
    private javax.swing.JTextField head2;
    private javax.swing.JTextField head3;
    private javax.swing.JTextField inputX;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel note10;
    private javax.swing.JLabel note11;
    private javax.swing.JLabel note12;
    private javax.swing.JLabel note9;
    private javax.swing.JLabel notes;
    private javax.swing.JLabel pKanan1;
    private javax.swing.JLabel pKanan2;
    private javax.swing.JLabel pKanan3;
    private javax.swing.JLabel pKanan4;
    private javax.swing.JLabel pKiri1;
    private javax.swing.JLabel pKiri2;
    private javax.swing.JLabel pKiri3;
    private javax.swing.JLabel pKiri4;
    private javax.swing.JPanel page;
    private javax.swing.JTextField tail1;
    private javax.swing.JTextField tail2;
    private javax.swing.JTextField tail3;
    private javax.swing.JTextField tail4;
    private javax.swing.JPanel title;
    private javax.swing.JTextField var1;
    private javax.swing.JTextField var2;
    private javax.swing.JTextField var3;
    private javax.swing.JTextField var4;
    private javax.swing.JTextField var5;
    private javax.swing.JTextField var6;
    private javax.swing.JTextField var7;
    private javax.swing.JTextField var8;
    private javax.swing.JTextField varx;
    private javax.swing.JTextField vary;
    // End of variables declaration//GEN-END:variables
}